# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/kairo/OneDrive/Documentos/Tec/10mo/FPGA/XADC_BIPOLAR_1/.Xil/Vivado-23396-DESKTOP-2HUJH4V/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z007sclg400-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include c:/Users/kairo/OneDrive/Documentos/Tec/10mo/FPGA/XADC_BIPOLAR_1/XADC_BIPOLAR_1.srcs/sources_1/bd/design_1/ipshared/c923 D:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      rt::read_verilog -include c:/Users/kairo/OneDrive/Documentos/Tec/10mo/FPGA/XADC_BIPOLAR_1/XADC_BIPOLAR_1.srcs/sources_1/bd/design_1/ipshared/c923 {
      C:/Users/kairo/OneDrive/Documentos/Tec/10mo/FPGA/XADC_BIPOLAR_1/.Xil/Vivado-23396-DESKTOP-2HUJH4V/realtime/design_1_pwm_0_0_stub.v
      C:/Users/kairo/OneDrive/Documentos/Tec/10mo/FPGA/XADC_BIPOLAR_1/.Xil/Vivado-23396-DESKTOP-2HUJH4V/realtime/design_1_xadc_wiz_0_0_stub.v
      C:/Users/kairo/OneDrive/Documentos/Tec/10mo/FPGA/XADC_BIPOLAR_1/.Xil/Vivado-23396-DESKTOP-2HUJH4V/realtime/design_1_clk_wiz_0_0_stub.v
      C:/Users/kairo/OneDrive/Documentos/Tec/10mo/FPGA/XADC_BIPOLAR_1/.Xil/Vivado-23396-DESKTOP-2HUJH4V/realtime/design_1_compuerta_xor_0_0_stub.v
      C:/Users/kairo/OneDrive/Documentos/Tec/10mo/FPGA/XADC_BIPOLAR_1/XADC_BIPOLAR_1.srcs/sources_1/new/compuerta_xor.v
      c:/Users/kairo/OneDrive/Documentos/Tec/10mo/FPGA/XADC_BIPOLAR_1/XADC_BIPOLAR_1.srcs/sources_1/bd/design_1/ipshared/f044/hdl/xlslice_v1_0_vl_rfs.v
      c:/Users/kairo/OneDrive/Documentos/Tec/10mo/FPGA/XADC_BIPOLAR_1/XADC_BIPOLAR_1.srcs/sources_1/bd/design_1/ip/design_1_xlslice_0_0/synth/design_1_xlslice_0_0.v
      c:/Users/kairo/OneDrive/Documentos/Tec/10mo/FPGA/XADC_BIPOLAR_1/XADC_BIPOLAR_1.srcs/sources_1/bd/design_1/ipshared/66e7/hdl/xlconstant_v1_1_vl_rfs.v
      c:/Users/kairo/OneDrive/Documentos/Tec/10mo/FPGA/XADC_BIPOLAR_1/XADC_BIPOLAR_1.srcs/sources_1/bd/design_1/ip/design_1_xlconstant_1_0/synth/design_1_xlconstant_1_0.v
      c:/Users/kairo/OneDrive/Documentos/Tec/10mo/FPGA/XADC_BIPOLAR_1/XADC_BIPOLAR_1.srcs/sources_1/bd/design_1/ip/design_1_xlconstant_2_0/synth/design_1_xlconstant_2_0.v
      c:/Users/kairo/OneDrive/Documentos/Tec/10mo/FPGA/XADC_BIPOLAR_1/XADC_BIPOLAR_1.srcs/sources_1/bd/design_1/ip/design_1_xlconstant_0_1/synth/design_1_xlconstant_0_1.v
      C:/Users/kairo/OneDrive/Documentos/Tec/10mo/FPGA/XADC_BIPOLAR_1/XADC_BIPOLAR_1.srcs/sources_1/bd/design_1/synth/design_1.v
      C:/Users/kairo/OneDrive/Documentos/Tec/10mo/FPGA/XADC_BIPOLAR_1/XADC_BIPOLAR_1.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
    }
      rt::read_vhdl -lib xil_defaultlib C:/Users/kairo/OneDrive/Documentos/Tec/10mo/FPGA/XADC_BIPOLAR_1/XADC_BIPOLAR_1.srcs/sources_1/imports/Escritorio/DAC_pwm.vhd
      rt::read_vhdl -lib xpm D:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top design_1_wrapper
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/Users/kairo/OneDrive/Documentos/Tec/10mo/FPGA/XADC_BIPOLAR_1/.Xil/Vivado-23396-DESKTOP-2HUJH4V/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
